name: Dockset

on:
  workflow_dispatch:
    inputs:
      crystalVersion:
        description: "Crystal version"
        required: true

jobs:
  build:
    name: Build dockset for Crystal version ${{ github.event.inputs.crystalVersion }}
    runs-on: macos-latest

    steps:
      - name: Download source
        uses: actions/checkout@v2

      - name: Install dependencies
        run: brew bundle

      - name: Download docs
        run: ./download.sh
        env:
          CRYSTAL_VERSION: ${{ github.event.inputs.crystalVersion }}

      - name: Build docset
        run: ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Crystal
          path: Crystal.tgz
